# Zola configuration
# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://brianvanburken.nl"
title = "Brian van Burken"
description = "Personal blog of Brian van Burken"
default_language = "en"

# Build settings
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["feed.xml"]

# Disable syntax highlighting - handled by Gulp/Shiki
# Note: This is set in [markdown] section

# Taxonomies disabled - tags page built manually
taxonomies = []

# Markdown settings
[markdown]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
github_source = "https://github.com/brianvanburken/brianvanburken.github.io/tree/master/"
date_format = "%Y-%m-%d"
